blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path("<int:article_id>/", views.blog_article, name="blog_article"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import serve, static
from django.views.generic import TemplateView
import notifications.urls
from django.views import generic


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('pwd_reset/', include(("password_reset.urls", 'pwd_reset'), namespace='pwd_reset')),
    path('article/', include("article.urls", namespace='article')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    # set URL for files in media
    #re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('image/', include('image.urls', namespace='image')),
    path('course/', include('course.urls', namespace='course')),
    path('', include('social_django.urls', namespace='social')),
    # path('search/', include('haystack.urls')),
    path('monitor/', include('monitor.urls', namespace='monitor')),
    path('/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('astrology/', include('astrologychart.urls', namespace='astrology')),
    path('MP_verify_h59nnjWDWorPL64o.txt', TemplateView.as_view(template_name='MP_verify_h59nnjWDWorPL64o.txt', content_type='text/plain')),
    re_path(r'^$', generic.RedirectView.as_view(
        url='/workflow/', permanent=False)),
    # re_path(r'', include(frontend_urls)),
    re_path(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'


urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),

]

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from article.models import ArticlePost


# Create your views here.

class CommentNoticeListView(LoginRequiredMixin, ListView):
    context_object_name = 'notices'
    template_name = 'notice/list.html'
    login_url = '/account/new-login/'

    def get_queryset(self):
        return self.request.user.notifications.unread()


class CommentNoticeUpdateView(View):
    def get(self, request):
        notice_id = request.GET.get('notice_id')
        if notice_id:
            article = ArticlePost.objects.get(id=request.GET.get('article_id'))
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect(article.get_url_path())
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{%  extends "base.html" %}
{%  load staticfiles %}

{% block title %}
消息通知
{% endblock title %}

{% block content %}
<div class="container">
    {% if notices %}
    <div class="row mt-4 ml-4">
        <a href="{% url 'notice:update' %}" class="btn btn-warning" role="button">清空消息通知</a>
    </div>
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    <a href="{% url 'notice:update' %}?article_id={{notice.target.id}}&notice_id={{ notice.id }}" target="_blank"  rel="noopener noreferrer">
                        <span style="color: blue">{{notice.actor}}</span>在文章《<span style="color:red">{{notice.target.title}}</span>》中{{notice.verb}}。<span style="margin-left:20px;color:grey;">{{notice.timestamp| date:"Y/m/d H:i"}}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <div class="row mt-4 ml-4">
        <a href="{% url 'notice:update' %}" class="btn btn-warning" style="background-color:blue" role="button">目前还没有消息通知哦～</a>
    </div>
    {% endif %}
</div>
<style>
    #notice_link a:link {color:black;}
    #notice_link a:visited {color:lightgrey;}
</style>
{% endblock content %}