article/urls.py
from django.urls import path, re_path, include
from . import views, list_views


app_name = 'article'


urlpatterns = [
    path('article-column/', views.article_column, name="article_column"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),
    path('del-column/', views.del_article_column, name="del_article_column"),
    path('article-post/', views.article_post, name="article_post"),
    path('del-article/', views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),

    path('article-list/', views.article_list, name="article_list"),
    path('article-list-published/', views.article_list_published, name="article_list_published"),
    path('article-list-draft/', views.article_list_draft, name="article_list_draft"),
    path('article-list-processed/', views.article_list_processed, name="article_list_processed"),
    #path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),
    re_path(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('blog-image-upload/', views.blog_img_upload, name="blog_img_upload", ),
    path('blog-image-upload-drag/', views.blog_img_upload_drag, name="blog_img_upload_drag", ),
    path('blog-video-upload-drag/', views.blog_video_upload_drag, name="blog_video_upload_drag", ),
    path('blog-file-upload-drag/', views.blog_file_upload_drag, name="blog_file_upload_drag", ),
    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('list-article-titles/<username>/', list_views.article_titles, name="author_articles"),
    path('list-article-detail/<int:id>/<slug:slug>/', list_views.article_detail, name="list_article_detail"),
    #re_path(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    path('like-article/', list_views.like_article, name="like_article"),
    path('like-comment/', list_views.like_comment, name="like_comment"),
    path('rename-tag/', views.rename_article_tag, name="rename_article_tag"),
    path('article-tag/', views.article_tag, name="article_tag"),
    path('del-article-tag/', views.del_article_tag, name="del_article_tag"),
    path('article/search.html', views.MySearchView(), name="haystack_search"),
    path('column-filter/<column_filter>/', list_views.column_filter, name="column_filter"),
    path('tag-filter/<tag_filter>/', list_views.tag_filter, name="tag_filter"),
    path('answer-submit/', list_views.answer_submit, name="answer_submit"),
    path('submit-approve/', views.submit_approve, name="submit_approve"),
    path('undo-approve/', views.undo_approve, name="undo_approve"),
    path('queue-approve/<int:article_id>/', views.queue_approve, name="queue_approve"),
    path('list-task/', views.list_task, name="list_task"),
    path('approve-article/', views.approve_article, name="approve_article"),

]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path("<int:article_id>/", views.blog_article, name="blog_article"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import serve, static
from django.views.generic import TemplateView
import notifications.urls
from django.views import generic


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('pwd_reset/', include(("password_reset.urls", 'pwd_reset'), namespace='pwd_reset')),
    path('article/', include("article.urls", namespace='article')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    # set URL for files in media
    #re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('image/', include('image.urls', namespace='image')),
    path('course/', include('course.urls', namespace='course')),
    path('', include('social_django.urls', namespace='social')),
    # path('search/', include('haystack.urls')),
    path('monitor/', include('monitor.urls', namespace='monitor')),
    path('/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('astrology/', include('astrologychart.urls', namespace='astrology')),
    path('MP_verify_h59nnjWDWorPL64o.txt', TemplateView.as_view(template_name='MP_verify_h59nnjWDWorPL64o.txt', content_type='text/plain')),
    re_path(r'^$', generic.RedirectView.as_view(
        url='/workflow/', permanent=False)),
    # re_path(r'', include(frontend_urls)),
    re_path(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag, CommentMulti, ArticleProcessFlow, ProcessStateRecord
from.models import Question, Answer


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body", "voteanonymousornot", "usercanvote", "votedeadline", "approved")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)


class CommentMultiForm(forms.ModelForm):
    class Meta:
        model = CommentMulti
        fields = ("comment_content", )


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', 'required', 'question_type', 'choices', 'survey')


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('question', 'answer', 'survey', 'interviewer', 'interviewee')


class ArticleProcessFlowForm(forms.ModelForm):
    class Meta:
        model = ArticleProcessFlow
        fields = '__all__'


class ProcessStateRecordForm(forms.ModelForm):
    class Meta:
        model = ProcessStateRecord
        fields = '__all__'

article/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm, QuestionForm, AnswerForm, ArticleProcessFlowForm
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from PIL import Image
from mysite.settings import MEDIA_ROOT
import os
import random
from slugify import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from .models import CommentMulti
from haystack.views import SearchView
from django.conf import settings
from django.template import Context, Template
from django.utils import timezone
from django.contrib.auth.models import User
from .models import ArticleProcessFlow, ProcessStateRecord


# Create your views here.


@login_required(login_url='/account/new-login')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        print(columns.count())
        for column in columns:
            print(column.column)
        user_request = request.user
        articles_list = ArticlePost.objects.filter(author=request.user, approved=False)
        articles_list_published = ArticlePost.objects.filter(author=request.user, approved=True)
        list_draft = []
        list_processed = []
        for art in articles_list:
            process = ArticleProcessFlow.objects.filter(article=art)
            if process.count() == 0:
                list_draft.append(art)
            else:
                list_processed.append(art)
        num_draft = len(list_draft)
        num_processed = len(list_processed)
        num_published = len(articles_list_published)

        processes_list_ori = ArticleProcessFlow.objects.filter(approvers=request.user)
        processes_list = []
        for process in processes_list_ori:
            if process.state_process.last().this_step_state == 1:
                if user_request in process.state_process.last().next_step_user.all():
                    processes_list.append(process)
        num_process = len(processes_list)
        num_all = [num_draft, num_processed, num_published, num_process]
        return render(request, "article/column/article_column.html", {"columns": columns, "column_form": column_form, "user_request": user_request, "num_all": num_all})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if len(column_name) == 0:

            return HttpResponse(3)
        elif columns:

            return HttpResponse(2)
        else:
            newcolumn = ArticleColumn.objects.create(user=request.user, column=column_name)
            dict_id = {"newcolumn_id": newcolumn.id}
            return HttpResponse(json.dumps(dict_id), content_type='application/json')


@login_required(login_url='/account/new-login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/new-login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/new-login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        user_request = request.user
        articles_list = ArticlePost.objects.filter(author=request.user, approved=False)
        articles_list_published = ArticlePost.objects.filter(author=request.user, approved=True)
        list_draft = []
        list_processed = []
        for art in articles_list:
            process = ArticleProcessFlow.objects.filter(article=art)
            if process.count() == 0:
                list_draft.append(art)
            else:
                list_processed.append(art)
        num_draft = len(list_draft)
        num_processed = len(list_processed)
        num_published = len(articles_list_published)

        processes_list_ori = ArticleProcessFlow.objects.filter(approvers=request.user)
        processes_list = []
        for process in processes_list_ori:
            if process.state_process.last().this_step_state == 1:
                if user_request in process.state_process.last().next_step_user.all():
                    processes_list.append(process)
        num_process = len(processes_list)
        num_all = [num_draft, num_processed, num_published, num_process]
        return render(request, "article/tag/tag_list.html", {"article_tags": article_tags, "article_tag_form": article_tag_form, "user_request": user_request, "num_all": num_all})
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        tag_name = request.POST['tag']
        tags = ArticleTag.objects.filter(author_id=request.user.id, tag=tag_name)
        if len(tag_name) == 0:
            return HttpResponse(3)
        if tag_post_form.is_valid():
            if tags:
                return HttpResponse(2)
            else:
                try:
                    tag_last = ArticleTag.objects.last()
                    new_tag = tag_post_form.save(commit=False)
                    new_tag.author = request.user
                    new_tag.save()
                    dict_id = {"tag_last_id": tag_last.id, "new_tag_id": new_tag.id}
                    return HttpResponse(json.dumps(dict_id), content_type='application/json')
                except:
                    return HttpResponse(4)
        else:
            return HttpResponse(3)


@login_required(login_url='/account/new-login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    print(tag_id)
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/new-login')
@require_POST
@csrf_exempt
def rename_article_tag(request):
    tag_name = request.POST["tag_name"]
    tag_id = request.POST['tag_id']
    try:
        line = ArticleTag.objects.get(id=tag_id)
        line.tag = tag_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


import sys, traceback
from django.contrib.auth.models import Group


@login_required(login_url='/account/new-login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        print('da')
        print(article_post_form)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            print('55')
            try:
                survey = request.POST['survey']
                print(survey)
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                print(request.POST['column_id'])
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                if survey:
                    interviewees = eval(request.POST['interviewees'])
                    deadline = request.POST['deadline']
                    anonymous = request.POST['anonymous']
                    if interviewees:
                        print(interviewees)
                        print(type(interviewees))
                        for user in interviewees:
                            print(user)
                            user_obj = User.objects.filter(username=user)
                            print(user_obj[0])
                            if user_obj:
                                new_article.usercanvote.add(user_obj[0])
                    if deadline:
                        print(deadline)
                        new_article.votedeadline = deadline
                    if anonymous:
                        print(anonymous)
                        new_article.voteanonymousornot = anonymous
                new_article.save()
                print(request.POST['tags'])
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                if survey:
                    for question in json.loads(survey):
                        question_form = QuestionForm().save(commit=False)
                        question_form.text = question[0]
                        question_form.question_type = question[1]
                        question_form.choices = question[2]
                        question_form.required = question[3]
                        question_form.survey = new_article
                        question_form.save()
                return HttpResponse("1")
            except Exception as e:
                print(traceback.format_exc())
                return HttpResponse("2")
        else:
            print(traceback.format_exc())
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()

templates/article/approve/approve-article.html
{% extends 'viewflow/base_module.html' %}
{% load i18n viewflow viewflow_frontend material_form material_frontend %}

{% block breadcrumbs_items %}
{% include 'viewflow/includes/breadcrumb_category.html' %}
<a href="{% flowurl activation.flow_class 'index' %}?{{ request|query_back }}">{{ activation.flow_class.process_title }}</a>
<a href="{% flowurl activation.process 'detail' %}?{{ request|query_back }}">#{{ activation.process.pk }}</a>
<a class="active" href="{% flowurl activation.task 'detail' %}?{{ request|query_back }}">{{ activation.flow_task }} / #{{ activation.task.pk }}</a>
{% endblock %}


{% block content %}
{% block left-panel %}
<div class="left-panel">
  <div class="card">
    <dmc-form>
      <form role="form" method="POST" enctype="multipart/form-data">
        <div class="card-content">
          <div class="card-title">
            {{ activation.task.summary|default:activation.task.flow_task }}
            <h6>{{ activation.process.summary }}</h6>
          </div>
          {% block task_form %}
          {% csrf_token %}
          {% form form=form %}{% endform %}
          {{ activation.management_form }}
          {% endblock %}
        </div>
        <div class="card-action">
          <div class="row">
            {% block task_actions %}
            <div class="col s3">
              <a class="btn btn-flat black-text" href="{% flowurl activation.task 'detail' %}?{{ request|query_back }}">{% trans 'Detail' %}</a>
            </div>
            <div class="col s9 right-align">
              <button type="submit" name="_continue" class="btn btn-flat">{% trans 'Done and continue on this process' %}</button>
              <button type="submit" name="_done" class="btn primary white-text">{% trans 'Done' %}</button>
            </div>
            {% endblock %}
          </div>
        </div>
      </form>
    </dmc-form>
  </div>
</div>
{% endblock %}
{% block right-panel %}
<div class="right-panel">
  {% include_process_data activation.process %}
</div>
{% endblock %}
{% endblock %}

templates/article/approve/process_data.html
<div class="input-field">
  <i class="material-icons prefix">all_out</i>
  <input type="text" readonly value="{{ process.planet }}">
  <label class="active">Planet</label>
</div>
<div class="input-field">
  <i class="material-icons prefix">create</i>
  <textarea class="materialize-textarea" readonly>{{ process.description }}</textarea>
  <label class="active">Description</label>
</div>
<div style="padding-left:3em">
  <label>Approved<br/><br/></label>
  <div class="switch">
    <label>
      No
      <input type="checkbox" disabled="disabled" {% if process.approved %}checked{% endif %}>
      <span class="lever"></span>
      Yes
    </label><br/><br/>
  </div>
</div>
{% if process.drop_status %}
<div class="input-field">
  <i class="material-icons prefix">file_download</i>
  <input type="text" readonly value="{{ process.get_drop_status_display }}">
  <label class="active">Drop Status</label>
</div>
{% if process.delivery_report %}
<div class="input-field">
  <i class="material-icons prefix">assignment_finished</i>
  <textarea class="materialize-textarea" readonly>{{ process.delivery_report }}</textarea>
  <label class="active">Delivery Report</label>
</div>
{% endif %}
{% endif %}

templates/article/approve/process_detail.html
{% extends 'base.html' %}
{% load viewflow %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">Parcel #{{ process.pk }}</h2>
<div class="row">
  <div class="col s12 m6 l5 offset-m3 offset-l2">
    <table>
      <thead>
        <tr>
          <td>#</td>
          <td>Description</td>
          <td>Owner</td>
          <td>Status</td>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
        {% flowurl task user=request.user as task_url %}
        <tr>
          <td>
            {% if task_url %}<a href="{{ task_url}}">{{ task.pk }}</a>{% else %}{{ task.pk }}{% endif %}
          </td>
          <td>{{ task.summary|default:task.flow_task }}</td>
          <td>{{ task.owner }}</td>
          <td>{{ task.status }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col s12 m6 l4 offset-m3 offset-l1">
    {% include_process_data process %}
  </div>
</div>
{% endblock %}

templates/article/approve/process_list.html
{% extends 'base.html' %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">{{ view.flow_class }}</h2>
<div class="row">
  <div class="col s12 m12 l8 offset-l2">
    <table id="table" class="table bordered">
      <thead>
        <td>#</td>
        <td>Sent</td>
        <td>Planet</td>
        <td>Approved</td>
        <td>Status</td>
      </thead>
      <tbody>
        {% for process in process_list %}
        <tr>
          <td>
            <a href="{% url 'parcel:delivery:detail' process.pk %}">{{ process.pk }}</a>                        
          </td>
          <td>{{ process.created }}</td>
          <td>{{ process.planet }}</td>
          <td>{{ process.approved|yesno:"Yes,No" }}</td>
          <td>
            {% if process.finished %}
            {{ process.get_drop_status_display }}
            {% else %}
            {{ process.status }}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/article/approve/queue.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}
{% block content %}
<div>
    <h4>流程记录</h4>
  <h5>文章:{{article.title}}</h5>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>当前处理人</td>
            <td>当前处理</td>
            <td>当前状态</td>
            <td>处理意见</td>
           <td>处理时间</td>
           <td>下一步处理人</td>
        </tr>
        {% for state in states %}
        <tr id={{state.id}}>
            <td>{{forloop.counter}}</td>
            <td><a href="{% url 'article:author_articles' state.this_step_user.username %}" class="hvr-icon-buzz" style="margin-right:8px;color:#6495ED;" ><i style="margin-right:4px;color:#6495ED;" class="fas fa-user hvr-icon"></i>{{state.this_step_user.first_name}}</a></td>
            <td>
                {% if state.this_step_handle == 0 %}
                      草稿制作
                  {% elif state.this_step_handle == 1  %}
                    发起审批
                 {% elif state.this_step_handle == 2  %}
                    同意
                 {% elif state.this_step_handle == 3  %}
                     驳回
                 {% elif state.this_step_handle == 4  %}
                      撤回
                 {% elif state.this_step_handle == 5  %}
                     删除
                {% endif %}
                 </td>
            <td>{% if state.this_step_state == 0 %}
                      草稿
                  {% elif state.this_step_state == 1  %}
                    审批中
                 {% elif state.this_step_state == 2  %}
                    已发布
                 {% elif state.this_step_state == 3  %}
                     被驳回
                 {% elif state.this_step_state == 4  %}
                      已撤回
                 {% elif state.this_step_state == 5  %}
                     已删除
                {% endif %}
            </td>
            <td style="text-align:center;vertical-align:middle;">
              {{state.this_step_opinion}}
                       </td>
          <td>{{state.this_step_time}}</td>
            <td>
            {% for user in  state.next_step_user.all %}
                <span><a href="{% url 'article:author_articles' user.username %}" class="hvr-icon-buzz" style="margin-right:8px;color:#6495ED;" ><i style="margin-right:4px;color:#6495ED;" class="fas fa-user hvr-icon"></i>{{user.first_name}}</a>,&nbsp</span>
                 {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
        {% include "paginator.html" %}
</div>


{% endblock %}

templates/article/approve/start.html
{% extends 'base.html' %}
{% load material_form %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">{{ activation.flow_task.task_title }}</h2>
<div class="row">
    <div class="col s12 m6 l4 offset-m3 offset-l4">
        <form method="POST">
            {% csrf_token %}
            {% form form=form %} {% endform %}
            {{ activation.management_form }}
            <div class="right">
                <button type="submit" name="_start" class="btn">Start</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/article/approve/task.html
{% extends 'base.html' %}
{% load material_form viewflow %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">
  <a href="{% url 'parcel:delivery:detail' activation.process.pk %}">Parcel #{{ activation.process.pk }}</a> &rang; {{ activation.flow_task }}
</h2>
<form method="POST">
  {% csrf_token %}
  <div class="row">
    <div class="col s12 m6 l6 offset-m3 offset-l2">
      {% form form=form %} {% endform %}
      {{ activation.management_form }}
      <div class="right">
      </div>
    </div>
    <div class="col s12 m6 l4 offset-m3">
      {% include_process_data activation.process %}
    </div>
  </div>
  <div class="row">
    <div class="col s12 m6 l10 offset-m3 offset-l2">
      <button type="submit" name="_start" class="btn">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

templates/article/approve/task_assign.html
{% extends 'parcel/delivery/task_base.html' %}

{% block task_actions %}
<form method="POST">
  {% csrf_token %}
  <button type="submit" name="_assign" class="btn">Assign</button>
</form>
{% endblock %}

templates/article/approve/task_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}
{% block content %}
<div>
    <h4>工单处理</h4>
  <h5>文章:{{article.title}}</h5>
    <table class="table table-hover">
        <tr>
            <td  style="text-align:center;vertical-align:middle;">序号</td>
            <td  style="text-align:center;vertical-align:middle;">工单发起人</td>
            <td  style="text-align:center;vertical-align:middle;">文章</td>
            <td  style="text-align:center;vertical-align:middle;">工单发起时间</td>
            <td  style="text-align:center;vertical-align:middle;">处理</td>
        </tr>
        {% for process in processes %}
        <tr id={{process.id}}>
            <td  style="text-align:center;vertical-align:middle;">{{forloop.counter}}</td>
            <td  style="text-align:center;vertical-align:middle;"><a href="{% url 'article:author_articles' process.applicant %}" class="hvr-icon-buzz" style="margin-right:8px;" ><i style="margin-right:4px;" class="fas fa-user hvr-icon"></i>{{process.applicant.first_name}}</a></td>
            <td  style="text-align:center;vertical-align:middle;"><a href="{{ process.article.get_absolute_url }}" data-toggle="tooltip" data-placement="top" title="查看文章">{{process.article.title}}</a> </td>
            <td  style="text-align:center;vertical-align:middle;">{{process.application_time}}</td>
            <td  style="text-align:center;vertical-align:middle;"><a name="approve" href="javascript:" onclick="approve_article(this,{{process.id}})"><span class="glyphicon glyphicon-transfer"  data-toggle="tooltip" data-placement="top" title="审批"></span></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include "paginator.html" %}
</div>

<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

<script type="text/javascript">
    function approve_article(the, process_id){
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["600px", "400px"],
            title: "审批",
            content: '<div class="text-center" style="margin-top:20px"><div class="layui-input-inline"><input class="ccc" id = "approyes" name="choice" type="radio" lay-filter="choice"  value="1"  checked=true >同意 <input  class="ccc"  id = "approno" name="choice" type="radio"  lay-filter="choice" value="0" style="margin-left:10px" >驳回 </div><div style="margin-top:10px">审批意见:</div><div style="margin-top:8px"><textarea id="opinion"   cols="40"   rows="6"   style="OVERFLOW:   hidden" placeholder="同意发布">同意发布。</textarea></div> </div>',
            btn: ['提交', '取消'],
            yes: function(index, layero){

               $(".layui-layer-btn0").attr('disabled',true);
                          $(".layui-layer-btn0").css("pointer-events","none");
                          $(".layui-layer-btn0").text("提交中...");
                          var approve_state;
                        if($("#approyes").prop('checked')==true)
                        {approve_state = "yes";}
                        else
                        {approve_state = "no"}
                        var opinion = $("#opinion").val();
                        console.log(approve_state);
                        console.log(opinion);

                    $.ajax({
                        url: '{% url "article:approve_article" %}',
                        type: 'POST',
                        data: { "process_id":process_id, "approve_state":approve_state, "opinion":opinion},
                        success:function(e){
                                if(e=="2"){
                                  $(".layui-layer-btn0").attr('disabled',false);
                                     $(".layui-layer-btn0").css("pointer-events","auto");
                                    $(".layui-layer-btn0").text("确认");
                                    layer.msg("出错了!");
                                    }
                                    else if(e=="4")
                                    {layer.msg("流程已被撤回!");parent.location.reload();}
                                    else if(e=="3")
                                    {layer.msg("流程已被其他人处理!");parent.location.reload();}
                                    else if(e=="5")
                                    {layer.msg("流程已被其他人处理!");parent.location.reload();}
                                    else {

                                     $(".layui-layer-btn0").attr("disabled",true);
                                    $(".layui-layer-btn0").css("pointer-events","none");
                                    layer.msg("提交成功!");
                                    parent.location.reload();}
                             },
                         });

                   },
            btn2: function(index, layero){
                    layer.close(index);
                    }
           });
           $(".ccc").bind('click', function(){
                  $("#opinion").text("同意发布。");
                  var sex = $("input[type=radio]:checked").val();
                   if(sex=="1") {$("#opinion").text("同意发布。"); }
                   else {$("#opinion").text("请修改！");}


           });

       }
</script>

{% endblock %}

templates/article/approve/task_unassign.html
{% extends 'parcel/delivery/task_base.html' %}

{% block task_actions %}
<form method="POST">
  {% csrf_token %}
  <button type="submit" name="run_action" class="btn">Unassign</button>
</form>
{% endblock %}